### ISSUE TITLE
 SKR 3 EZ and wire limits question.

### ISSUE THREAD

**Issue by Demitrius** [dresco/STM32H7xx#13]
Hello Jon,

I found limits wire scheme, with resistors and capacitor.

Scheme attached.
![2023-03-06 11 15 55](https://user-images.githubusercontent.com/2479194/223056288-b162c2c6-33e8-42b0-91e3-7e22249405fa.jpg)

What do you think, need wire same for SKR 3 EZ?

In my build, I can connect 2 limits (start and end stops) to X-axis limit port, cable length about 3 meters.
May be better to add capacitor/resister?
<img width="729" alt="Снимок экрана 2023-03-06 в 11 22 02" src="https://user-images.githubusercontent.com/2479194/223056420-d30d234f-f562-48da-a0a8-066b046fa5a4.png">

**Comment by dresco** [comment]
Looking at the [schematic](https://github.com/bigtreetech/SKR-3/blob/master/Hardware%20(SKR%203%20EZ)/BIGTREETECH%20SKR%203%20EZ%20V1.0-SCH.pdf), they already have the onboard resistors and capacitors for the limit switches.

Ideally all the inputs would come through optocouplers for added protection, but I suppose it's a 3D printer board after all.. :shrug:

**Comment by Demitrius** [comment]
Completely agree, the optocouplers is definitely overhead.
I will do it as it is, without extra elements.

Jon, thanks for help. I appreciate it.
