### ISSUE TITLE
External driver on SKR 3 board

### ISSUE THREAD

**Issue by Demitrius** [dresco/STM32H7xx#15]
Hello Jon,

I think about wiring external driver to SKR board.
Similar https://www.moonsindustries.com/series/ssdc-series-step-servo-drives-a01030107

As I see, I need connect several pins from board to driver and all other as usual.
For example, a driver needs the Enable+, Step+ and Direction+ pins, and of course ground to some or all of the - connections, from the SKR.

What do you think about it? Possible?

**Comment by dresco** [comment]
Off the top of my head, I don't know how the the SKR board drives the motor logic outputs, possibly just 3.3v straight from the MCU?

This is probably where the 3d printer origins of this board start to show. A more CNC oriented board would likely have buffered outputs, opto-isolated inputs etc..
