### ISSUE TITLE
Problem with $X command

### ISSUE THREAD

**Issue by PaONEkaruchola** [dresco/STM32H7xx#21]
I am using a Nucleo-H743ZI board, I want to run it with grbl firmware, having an issue while killing the alarm, $X is not working, and showing errors.

**Comment by dresco** [comment]
Will need some context.. 

What build configuration?
What are the alarms / errors?
Are control and limit inputs inverted as necessary for your connections?

The realtime command `?` will show you the current alarm code and active pin states. There are also the `$LEV` & `$LIM` commands;

```
$LEV - output last control signal events.
$LIM - output current limit pins.
```

**Comment by PaONEkaruchola** [comment]
I am using GrblGru V5.1.18 software to send g-code to the controller. While turning off the alarm use the $X command it is not working. 
![IMG_20240222_172252865](https://github.com/dresco/STM32H7xx/assets/79260146/6dddcb75-72f6-4baa-86f0-d1844120a9de)

**Comment by dresco** [comment]
You will need to establish the cause of the alarm. Have you checked the state of the control and limit inputs as described above?

Note that grblHAL expects normally closed switches by default. Most likely cause (on a bare dev board) is that these inputs have not been inverted as needed in the settings..
