### ISSUE TITLE
Is posible use WIZCHIP W5500

### ISSUE THREAD

**Issue by semos2k** [dresco/STM32H7xx#27]
I have weact mini h723 and grblhal work nice, is posible use WIZCHIP W5500 for connect over ethernet cable ?

**Comment by dresco** [comment]
Hi, not currently I'm afraid. The only networking support is for the onboard MAC with external LAN8742 PHY chip.

There was a [question](https://github.com/grblHAL/STM32F7xx/discussions/16#discussioncomment-8677113) in the F7 repo about porting Wiznet code over from the F4 driver. So perhaps will be supported in the future..

**Comment by semos2k** [comment]
this feature has added and work.

**Comment by dresco** [comment]
Apologies, I meant to update this issue but forgot..
Glad you noticed the update! ;)
