### ISSUE TITLE
Hello, what is the maximum output frequency of the h743 pulse?

### ISSUE THREAD

**Issue by hanke-cnc** [dresco/STM32H7xx#5]
Sorry, I have sold my h7 development board before, there is no way to test, I have tested the f401, the stable output is 300khz, the f446 is 400khz

**Comment by dresco** [comment]
Hi, I can test for you. How are you comparing, just a single axis move, or while running a more typical job? Cheers..

**Comment by hanke-cnc** [comment]
> Hi, I can test for you. How are you comparing, just a single axis move, or while running a more typical job? Cheers..

Thank you so much!! Only one axis movement

**Comment by dresco** [comment]
Will get to 700khz stable output on a single axis move, is glitchy by 800khz..

**Comment by hanke-cnc** [comment]
> Will get to 700khz stable output on a single axis move, is glitchy by 800khz..

Danke, so cool!!

**Comment by hanke-cnc** [comment]
> Will get to 700khz stable output on a single axis move, is glitchy by 800khz..

hi, dresco, I haven't tried servo motors, I heard that servo motors need high pulse output control?
