### ISSUE TITLE
MODBUS on SKR3

### ISSUE THREAD

**Issue by Avalonnw** [dresco/STM32H7xx#9]
Am I missing something or there is no MODBUS spindle support for H7 boards?

**Comment by Avalonnw** [comment]
I can't figure out which pins to use. I am currently on a RTFM stage before
pulling my CNC for a controller upgrade apart. Unfortunately the FM part in
RTFM is not very user friendly :)

**Comment by dresco** [comment]
> I can't figure out which pins to use.

Try [this](https://github.com/dresco/STM32H7xx/issues/6#issuecomment-1328084821), is how I hooked my Huanyang VFD up to the SKR3..

**Comment by Avalonnw** [comment]
Thanks, I'll try.
I hope my spindle actually supports modbus :) It's mentioned in the manual in passing and I afraid RS485 components might be not populated on the VFD board. Will check tonight.
